// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using angular7_aspcore.Models;

namespace angular7_aspcore.Migrations
{
    [DbContext(typeof(ContactAppContext))]
    partial class ContactAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("angular7_aspcore.Models.Contact", b =>
                {
                    b.Property<long?>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("birth");

                    b.Property<string>("email");

                    b.Property<byte>("gender");

                    b.Property<string>("message");

                    b.Property<string>("name");

                    b.Property<string>("techno");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("angular7_aspcore.Models.Type", b =>
                {
                    b.Property<long?>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.HasKey("TypeId");

                    b.ToTable("Types");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Type");
                });

            modelBuilder.Entity("angular7_aspcore.Models.Vehicle", b =>
                {
                    b.Property<long?>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ContactId");

                    b.Property<string>("Make");

                    b.Property<string>("Model");

                    b.Property<string>("Registration");

                    b.Property<long?>("TypeId");

                    b.Property<string>("Version");

                    b.HasKey("VehicleId");

                    b.HasIndex("ContactId");

                    b.HasIndex("TypeId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("angular7_aspcore.Models.Bodystyle", b =>
                {
                    b.HasBaseType("angular7_aspcore.Models.Type");


                    b.ToTable("Bodystyle");

                    b.HasDiscriminator().HasValue("Bodystyle");
                });

            modelBuilder.Entity("angular7_aspcore.Models.Vehicle", b =>
                {
                    b.HasOne("angular7_aspcore.Models.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.HasOne("angular7_aspcore.Models.Bodystyle", "Bodystyle")
                        .WithMany()
                        .HasForeignKey("TypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
